################################################################################
#
# PCSXREARMED
#
################################################################################

PCSXREARMED_VERSION = HEAD
PCSXREARMED_SITE = git://github.com/notaz/pcsx_rearmed.git
#PCSXREARMED_DEPENDENCIES = sdl libpng zlib
PCSXREARMED_GIT_SUBMODULES = YES
PCSXREARMED_LICENSE = GPL-2.0
PCSXREARMED_LICENSE_FILES = COPYING

PCSXREARMED_MAKEFILE_CONFIGURATION  = TARGET=pcsx_rearmed
PCSXREARMED_MAKEFILE_CONFIGURATION += NO_CONFIG_MAK=yes
PCSXREARMED_MAKEFILE_CONFIGURATION += ARCH=arm64
PCSXREARMED_MAKEFILE_CONFIGURATION += HAVE_NEON=1
PCSXREARMED_MAKEFILE_CONFIGURATION += PLATFORM=generic
PCSXREARMED_MAKEFILE_CONFIGURATION += SOUND_DRIVERS=alsa
PCSXREARMED_MAKEFILE_CONFIGURATION += PLUGIN=
PCSXREARMED_MAKEFILE_CONFIGURATION += USE_DYNAREC=1

PCSXREARMED_SDL_INCLUDE = -I$(STAGING_DIR)/usr/include/SDL
PCSXREARMED_SDL_LIBRARY = -L$(STAGING_DIR)/usr/lib
PCSXREARMED_ALL_LIBRARIES = $(PCSXREARMED_SDL_LIBRARY) -ldl -lpthread -lSDL -lpng -lz

define PCSXREARMED_BUILD_CMDS
	$(SED) "s|-O2|-O3|g" $(@D)/Makefile
	CFLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_NOLTO) $(PCSXREARMED_SDL_INCLUDE)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_NOLTO) $(PCSXREARMED_SDL_INCLUDE)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(COMPILER_COMMONS_LDFLAGS_NOLTO) $(PCSXREARMED_ALL_LIBRARIES)" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" AR="$(TARGET_AR)" -C $(@D) -f Makefile $(PCSXREARMED_MAKEFILE_CONFIGURATION)
endef

define PCSXREARMED_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/pcsx_rearmed \
		$(TARGET_DIR)/usr/bin/pcsx_rearmed
endef

define PCSXREARMED_PRE_PATCH_FIXUP
	$(SED) 's/\r//g' $(@D)/libpcsxcore/plugins.c
	$(SED) 's/\r//g' $(@D)/libpcsxcore/plugins.h
endef

PCSXREARMED_PRE_PATCH_HOOKS += PCSXREARMED_PRE_PATCH_FIXUP

$(eval $(generic-package))
