################################################################################
#
# LIBRETRO_PPSSPP
#
################################################################################

LIBRETRO_PPSSPP_VERSION = v1.12.2
LIBRETRO_PPSSPP_SITE = git://github.com/hrydgard/ppsspp.git
LIBRETRO_PPSSPP_LICENSE = GPL-2.0
LIBRETRO_PPSSPP_LICENSE_FILES = LICENSE.TXT

LIBRETRO_PPSSPP_GIT_SUBMODULES=y
#LIBRETRO_PPSSPP_DEPENDENCIES = sdl2 zlib libzip zip ffmpeg snappy

LIBRETRO_PPSSPP_CONF_OPTS += \
	-DARM64=ON \
	-DARM_NO_VULKAN=ON \
	-DUSE_DISCORD=OFF \
	-DUSE_MINIUPNPC=OFF \
	-DUSING_GLES2=ON \
	-DHEADLESS=ON \
	-DLIBRETRO=ON \
	-DMOBILE_DEVICE=ON \
	-DSIMULATOR=OFF \
	-DUNITTEST=OFF \
	-DUSE_SYSTEM_LIBZIP=ON \
	-DUSE_SYSTEM_SNAPPY=OFF \
	-DUSE_SYSTEM_ZSTD=OFF \
	-DUSING_QT_UI=OFF \
	-Wno-dev \
	-DUSE_FFMPEG=ON \
	-DUSE_SYSTEM_FFMPEG=ON

define LIBRETRO_PPSSPP_PRE_CONFIGURE
	sed -E -i '/GIT_VERSION/s/unknown/$(LIBRETRO_PPSSPP_VERSION)/' $(@D)/git-version.cmake
endef

LIBRETRO_PPSSPP_PRE_CONFIGURE_HOOKS += LIBRETRO_PPSSPP_PRE_CONFIGURE

define LIBRETRO_PPSSPP_INSTALL_TO_TARGET
	mkdir $(TARGET_DIR)/system
	cp -R $(@D)/assets $(TARGET_DIR)/system/PPSSPP
	cp $(@D)/lib/*.so $(TARGET_DIR)/usr/lib/
	cp $(@D)/lib/ppsspp_libretro.so $(TARGET_DIR)/cores/ppsspp_libretro.so
endef

LIBRETRO_PPSSPP_INSTALL_TARGET_CMDS = $(LIBRETRO_PPSSPP_INSTALL_TO_TARGET)

LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_FLAGS="$(COMPILER_COMMONS_CFLAGS_EXE) -DEGL_NO_X11 -funsafe-math-optimizations"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(COMPILER_COMMONS_CXXFLAGS_EXE) -DEGL_NO_X11 -funsafe-math-optimizations"

LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="$(COMPILER_COMMONS_LDFLAGS_EXE)"

$(eval $(cmake-package))
